<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcCikpj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcCikpj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXcCikpj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXcCikpj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXcCikpj\App_KernelDevDebugContainer([
    'container.build_hash' => 'XcCikpj',
    'container.build_id' => '66f4ccb9',
    'container.build_time' => 1709069073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcCikpj');
