<?php

namespace ContainerBODXVmN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7ryQx7ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7ryQx7Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7ryQx7Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActualitesController::delete' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController::edit' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController::index' => ['privates', '.service_locator.Nrk9rvf', 'get_ServiceLocator_Nrk9rvfService', true],
            'App\\Controller\\ActualitesController::listp' => ['privates', '.service_locator.Nrk9rvf', 'get_ServiceLocator_Nrk9rvfService', true],
            'App\\Controller\\ActualitesController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActualitesController::show' => ['privates', '.service_locator.aW8jRcy', 'get_ServiceLocator_AW8jRcyService', true],
            'App\\Controller\\CommentairesController::delete' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController::edit' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController::index' => ['privates', '.service_locator.kIDxfvH', 'get_ServiceLocator_KIDxfvHService', true],
            'App\\Controller\\CommentairesController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommentairesController::show' => ['privates', '.service_locator.uB.FJP8', 'get_ServiceLocator_UB_FJP8Service', true],
            'App\\Controller\\FrontController::delete' => ['privates', '.service_locator.oZ6ony_', 'get_ServiceLocator_OZ6onyService', true],
            'App\\Controller\\FrontController::edit' => ['privates', '.service_locator.oZ6ony_', 'get_ServiceLocator_OZ6onyService', true],
            'App\\Controller\\FrontController::index' => ['privates', '.service_locator.o5fdk4C', 'get_ServiceLocator_O5fdk4CService', true],
            'App\\Controller\\FrontController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FrontController::show' => ['privates', '.service_locator.Vv3IHVH', 'get_ServiceLocator_Vv3IHVHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ActualitesController:delete' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController:edit' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController:index' => ['privates', '.service_locator.Nrk9rvf', 'get_ServiceLocator_Nrk9rvfService', true],
            'App\\Controller\\ActualitesController:listp' => ['privates', '.service_locator.Nrk9rvf', 'get_ServiceLocator_Nrk9rvfService', true],
            'App\\Controller\\ActualitesController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActualitesController:show' => ['privates', '.service_locator.aW8jRcy', 'get_ServiceLocator_AW8jRcyService', true],
            'App\\Controller\\CommentairesController:delete' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController:edit' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController:index' => ['privates', '.service_locator.kIDxfvH', 'get_ServiceLocator_KIDxfvHService', true],
            'App\\Controller\\CommentairesController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommentairesController:show' => ['privates', '.service_locator.uB.FJP8', 'get_ServiceLocator_UB_FJP8Service', true],
            'App\\Controller\\FrontController:delete' => ['privates', '.service_locator.oZ6ony_', 'get_ServiceLocator_OZ6onyService', true],
            'App\\Controller\\FrontController:edit' => ['privates', '.service_locator.oZ6ony_', 'get_ServiceLocator_OZ6onyService', true],
            'App\\Controller\\FrontController:index' => ['privates', '.service_locator.o5fdk4C', 'get_ServiceLocator_O5fdk4CService', true],
            'App\\Controller\\FrontController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FrontController:show' => ['privates', '.service_locator.Vv3IHVH', 'get_ServiceLocator_Vv3IHVHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ActualitesController::delete' => '?',
            'App\\Controller\\ActualitesController::edit' => '?',
            'App\\Controller\\ActualitesController::index' => '?',
            'App\\Controller\\ActualitesController::listp' => '?',
            'App\\Controller\\ActualitesController::new' => '?',
            'App\\Controller\\ActualitesController::show' => '?',
            'App\\Controller\\CommentairesController::delete' => '?',
            'App\\Controller\\CommentairesController::edit' => '?',
            'App\\Controller\\CommentairesController::index' => '?',
            'App\\Controller\\CommentairesController::new' => '?',
            'App\\Controller\\CommentairesController::show' => '?',
            'App\\Controller\\FrontController::delete' => '?',
            'App\\Controller\\FrontController::edit' => '?',
            'App\\Controller\\FrontController::index' => '?',
            'App\\Controller\\FrontController::new' => '?',
            'App\\Controller\\FrontController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActualitesController:delete' => '?',
            'App\\Controller\\ActualitesController:edit' => '?',
            'App\\Controller\\ActualitesController:index' => '?',
            'App\\Controller\\ActualitesController:listp' => '?',
            'App\\Controller\\ActualitesController:new' => '?',
            'App\\Controller\\ActualitesController:show' => '?',
            'App\\Controller\\CommentairesController:delete' => '?',
            'App\\Controller\\CommentairesController:edit' => '?',
            'App\\Controller\\CommentairesController:index' => '?',
            'App\\Controller\\CommentairesController:new' => '?',
            'App\\Controller\\CommentairesController:show' => '?',
            'App\\Controller\\FrontController:delete' => '?',
            'App\\Controller\\FrontController:edit' => '?',
            'App\\Controller\\FrontController:index' => '?',
            'App\\Controller\\FrontController:new' => '?',
            'App\\Controller\\FrontController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
