<?php

namespace ContainerBODXVmN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3tCK29Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h3tCK29' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h3tCK29'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaire' => ['privates', '.errored..service_locator.h3tCK29.App\\Entity\\Commentaires', NULL, 'Cannot autowire service ".service_locator.h3tCK29": it references class "App\\Entity\\Commentaires" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commentaire' => 'App\\Entity\\Commentaires',
            'entityManager' => '?',
        ]);
    }
}
