<?php

namespace ContainerBODXVmN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nrk9rvfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nrk9rvf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nrk9rvf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actualitesRepository' => ['privates', 'App\\Repository\\ActualitesRepository', 'getActualitesRepositoryService', true],
        ], [
            'actualitesRepository' => 'App\\Repository\\ActualitesRepository',
        ]);
    }
}
