<?php

namespace ContainerBODXVmN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OZ6onyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oZ6ony_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oZ6ony_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'front' => ['privates', '.errored..service_locator.oZ6ony_.App\\Entity\\Front', NULL, 'Cannot autowire service ".service_locator.oZ6ony_": it references class "App\\Entity\\Front" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'front' => 'App\\Entity\\Front',
        ]);
    }
}
