<?php

namespace ContainerWWx2V6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2rgwPdbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2rgwPdb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2rgwPdb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actualitesRepository' => ['privates', 'App\\Repository\\ActualitesRepository', 'getActualitesRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'actualitesRepository' => 'App\\Repository\\ActualitesRepository',
            'paginator' => '?',
        ]);
    }
}
