<?php

namespace ContainerWWx2V6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AW8jRcyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aW8jRcy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aW8jRcy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actualite' => ['privates', '.errored..service_locator.aW8jRcy.App\\Entity\\Actualites', NULL, 'Cannot autowire service ".service_locator.aW8jRcy": it references class "App\\Entity\\Actualites" but no such service exists.'],
        ], [
            'actualite' => 'App\\Entity\\Actualites',
        ]);
    }
}
