<?php

namespace ContainerWWx2V6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualitesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aW8jRcy.App\Entity\Actualites' shared service.
     *
     * @return \App\Entity\Actualites
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aW8jRcy": it references class "App\\Entity\\Actualites" but no such service exists.');
    }
}
