<?php

namespace ContainerWWx2V6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualites2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eM7s.2O.App\Entity\Actualites' shared service.
     *
     * @return \App\Entity\Actualites
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.eM7s.2O": it references class "App\\Entity\\Actualites" but no such service exists.');
    }
}
