<?php

namespace ContainerWWx2V6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentairesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h3tCK29.App\Entity\Commentaires' shared service.
     *
     * @return \App\Entity\Commentaires
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.h3tCK29": it references class "App\\Entity\\Commentaires" but no such service exists.');
    }
}
