<?php

namespace ContainerWWx2V6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFront2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oZ6ony_.App\Entity\Front' shared service.
     *
     * @return \App\Entity\Front
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oZ6ony_": it references class "App\\Entity\\Front" but no such service exists.');
    }
}
