<?php

namespace ContainerWvICmtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KIDxfvHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kIDxfvH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kIDxfvH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentairesRepository' => ['privates', 'App\\Repository\\CommentairesRepository', 'getCommentairesRepositoryService', true],
        ], [
            'commentairesRepository' => 'App\\Repository\\CommentairesRepository',
        ]);
    }
}
