<?php

namespace ContainerWvICmtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualitesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ActualitesRepository' shared autowired service.
     *
     * @return \App\Repository\ActualitesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ActualitesRepository'] = new \App\Repository\ActualitesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
