<?php

namespace ContainerWvICmtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualitesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ActualitesType' shared autowired service.
     *
     * @return \App\Form\ActualitesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ActualitesType'] = new \App\Form\ActualitesType();
    }
}
