<?php

namespace ContainerWvICmtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualitesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ActualitesController' shared autowired service.
     *
     * @return \App\Controller\ActualitesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ActualitesController'] = $instance = new \App\Controller\ActualitesController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ActualitesController', $container));

        return $instance;
    }
}
