<?php

namespace ContainerWvICmtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActualitesController::delete' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController::edit' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController::index' => ['privates', '.service_locator.Nrk9rvf', 'get_ServiceLocator_Nrk9rvfService', true],
            'App\\Controller\\ActualitesController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActualitesController::show' => ['privates', '.service_locator.aW8jRcy', 'get_ServiceLocator_AW8jRcyService', true],
            'App\\Controller\\CommentairesController::delete' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController::edit' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController::index' => ['privates', '.service_locator.kIDxfvH', 'get_ServiceLocator_KIDxfvHService', true],
            'App\\Controller\\CommentairesController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommentairesController::show' => ['privates', '.service_locator.uB.FJP8', 'get_ServiceLocator_UB_FJP8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ActualitesController:delete' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController:edit' => ['privates', '.service_locator.eM7s.2O', 'get_ServiceLocator_EM7s_2OService', true],
            'App\\Controller\\ActualitesController:index' => ['privates', '.service_locator.Nrk9rvf', 'get_ServiceLocator_Nrk9rvfService', true],
            'App\\Controller\\ActualitesController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActualitesController:show' => ['privates', '.service_locator.aW8jRcy', 'get_ServiceLocator_AW8jRcyService', true],
            'App\\Controller\\CommentairesController:delete' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController:edit' => ['privates', '.service_locator.h3tCK29', 'get_ServiceLocator_H3tCK29Service', true],
            'App\\Controller\\CommentairesController:index' => ['privates', '.service_locator.kIDxfvH', 'get_ServiceLocator_KIDxfvHService', true],
            'App\\Controller\\CommentairesController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommentairesController:show' => ['privates', '.service_locator.uB.FJP8', 'get_ServiceLocator_UB_FJP8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ActualitesController::delete' => '?',
            'App\\Controller\\ActualitesController::edit' => '?',
            'App\\Controller\\ActualitesController::index' => '?',
            'App\\Controller\\ActualitesController::new' => '?',
            'App\\Controller\\ActualitesController::show' => '?',
            'App\\Controller\\CommentairesController::delete' => '?',
            'App\\Controller\\CommentairesController::edit' => '?',
            'App\\Controller\\CommentairesController::index' => '?',
            'App\\Controller\\CommentairesController::new' => '?',
            'App\\Controller\\CommentairesController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActualitesController:delete' => '?',
            'App\\Controller\\ActualitesController:edit' => '?',
            'App\\Controller\\ActualitesController:index' => '?',
            'App\\Controller\\ActualitesController:new' => '?',
            'App\\Controller\\ActualitesController:show' => '?',
            'App\\Controller\\CommentairesController:delete' => '?',
            'App\\Controller\\CommentairesController:edit' => '?',
            'App\\Controller\\CommentairesController:index' => '?',
            'App\\Controller\\CommentairesController:new' => '?',
            'App\\Controller\\CommentairesController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
