<?php

namespace ContainerWvICmtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentairesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CommentairesController' shared autowired service.
     *
     * @return \App\Controller\CommentairesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CommentairesController'] = $instance = new \App\Controller\CommentairesController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\CommentairesController', $container));

        return $instance;
    }
}
