<?php

namespace ContainerXcCikpj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UB_FJP8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uB.FJP8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uB.FJP8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaire' => ['privates', '.errored..service_locator.uB.FJP8.App\\Entity\\Commentaires', NULL, 'Cannot autowire service ".service_locator.uB.FJP8": it references class "App\\Entity\\Commentaires" but no such service exists.'],
        ], [
            'commentaire' => 'App\\Entity\\Commentaires',
        ]);
    }
}
