<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvICmtA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvICmtA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWvICmtA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWvICmtA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWvICmtA\App_KernelProdContainer([
    'container.build_hash' => 'WvICmtA',
    'container.build_id' => 'ba50cc56',
    'container.build_time' => 1708371849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvICmtA');
