<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_actualites_index' => [[], ['_controller' => 'App\\Controller\\ActualitesController::index'], [], [['text', '/actualites/']], [], [], []],
    'app_actualites_new' => [[], ['_controller' => 'App\\Controller\\ActualitesController::new'], [], [['text', '/actualites/new']], [], [], []],
    'app_actualites_show' => [['id'], ['_controller' => 'App\\Controller\\ActualitesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/actualites']], [], [], []],
    'app_actualites_edit' => [['id'], ['_controller' => 'App\\Controller\\ActualitesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/actualites']], [], [], []],
    'app_actualites_delete' => [['id'], ['_controller' => 'App\\Controller\\ActualitesController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/actualites']], [], [], []],
    'app_commentaires_index' => [[], ['_controller' => 'App\\Controller\\CommentairesController::index'], [], [['text', '/commentaires/']], [], [], []],
    'app_commentaires_new' => [[], ['_controller' => 'App\\Controller\\CommentairesController::new'], [], [['text', '/commentaires/new']], [], [], []],
    'app_commentaires_show' => [['id'], ['_controller' => 'App\\Controller\\CommentairesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commentaires']], [], [], []],
    'app_commentaires_edit' => [['id'], ['_controller' => 'App\\Controller\\CommentairesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/commentaires']], [], [], []],
    'app_commentaires_delete' => [['id'], ['_controller' => 'App\\Controller\\CommentairesController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commentaires']], [], [], []],
];
